# Site settings
title: CachetHQ
email: jbrooksuk@me.com
description: > # this means to ignore newlines until "baseurl:"
  Cachet is an Open Source StatusPage.io alternative written in PHP
baseurl: ""
url: "http://cachethq.github.io" # the base hostname & protocol for your site
twitter_username: cachethq
github_username:  cachethq
timezone: Europe/London

# Build settings
markdown: kramdown

authors:
  james:
    display_name: James Brooks
    gravatar: 13616b6551a3854378f9e6fea964e519
    email: jbrooksuk@me.com
    web: http://james-brooks.uk
    twitter: jbrooksuk
    github: jbrooksuk
