# Site settings
title: CachetHQ
email: jbrooksuk@me.com
description: > # this means to ignore newlines until "baseurl:"
  Cachet is an Open Source StatusPage.io alternative written in PHP.
baseurl: ""
url: "http://cachethq.github.io" # the base hostname & protocol for your site
twitter_username: cachethq
github_username:  cachethq
timezone: Europe/London
project_title: Cachet

# Build settings
markdown: kramdown

# Theme customizations
colors:
  primary: "#F0F3F4" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#fff" #"#33004D"
  link: "#7ED321"
  link_hover: "#01579B"
  footer_heading: "#666"
  footer_content: "#999"

# Team members
authors:
  james:
    display_name: James Brooks
    position: Lead Developer
    gravatar: 13616b6551a3854378f9e6fea964e519
    email: jbrooksuk@me.com
    web: http://james-brooks.uk
    social:
      - title: envelope
        url: mailto:jbrooksuk@me.com
      - title: twitter
        url: https://twitter.com/jbrooksuk
      - title: github
        url: https://github.com/jbrooksuk
  thomas:
    display_name: Thomas Coleman
    position: Developer
    gravatar: f1caa5a80e83fad625ff3963a14ce3cf
    email: tom@ilikeprograms.com
    web: http://ilikeprograms.com
    social:
      - title: envelope
        url: mailto:tom@ilikeprograms.com
      - title: github
        url: https://github.com/ilikeprograms
  manavo:
    display_name: Philip Manavopoulos
    position: Developer
    gravatar: 604a97350ee8fa8940927e2a01c74038
    email: manavo@gmail.com
    web: http://manavo.com
    social:
      - title: envelope
        url: mailto:manavo@gmail.com
      - title: github
        url: https://github.com/manavo
  ehesp:
    display_name: Elliot Hesp
    position: Developer
    gravatar: 215db0deb447d97a916ea780771b8c64
    email: elliot.hesp@gmail.com
    web: https://elliothesp.co.uk
    social:
      - title: envelope
        url: mailto:elliot.hesp@gmail.com
      - title: github
        url: https://github.com/ehesp
  joecohens:
    display_name: Joe Cohens
    position: Developer
    # gravatar: Not sure?
    email: joseph.cohen@dinkbit.com
    web: http://joecohens.com
    social:
      - title: envelope
        url: mailto:joseph.cohen@dinkbit.com
      - title: github
        url: https://github.com/joecohens
  Hipsterbrown:
    display_name: Nick Hehr
    position: Designer
#    gravatar: not sure?
    email: headhipster@hipsterbrown.com
    web: http://hipsterbrown.com
    social:
        - title: twitter
          url: https://twitter.com/hipsterbrown
        - title: github
          url: https://github.com/hipsterbrown
        - title: codepen
          url: http://codepen.io/HipsterBrown

# Social links (footer)
social:
  - title: twitter
    url: https://twitter.com/cachethq
  - title: github
    url: https://github.com/cachethq

# About text
about: Open Source StatusPage.io alternative written in PHP.
