# Site settings
title: CachetHQ
email: jbrooksuk@me.com
description: > # this means to ignore newlines until "baseurl:"
  Cachet is an Open Source StatusPage.io alternative written in PHP.
baseurl: ""
url: "http://cachethq.github.io" # the base hostname & protocol for your site
twitter_username: cachethq
github_username:  cachethq
timezone: Europe/London
project_title: Cachet

# Build settings
markdown: kramdown

# Social links (footer)
social:
  - title: twitter
    url: https://twitter.com/cachethq
  - title: github
    url: https://github.com/cachethq

# About text
about: Open Source StatusPage.io alternative written in PHP.
